'use strict';

const _coffeescript = require('coffeescript');

const _coffeescript2 = _interopRequireDefault(_coffeescript);

function _interopRequireDefault(obj) {
	return obj && obj.__esModule ? obj : {default: obj};
}

// Generated by CoffeeScript 2.2.1
const _extends = Object.assign || function (target) {
	for (let i = 1; i < arguments.length; i++) {
		const source = arguments[i]; for (const key in source) {
			if (Object.prototype.hasOwnProperty.call(source, key)) {
				target[key] = source[key];
			}
		}
	} return target;
};

exports.name = 'coffeescript';

exports.inputFormats = ['coffee', 'coffeescript'];

exports.outputFormat = 'js';

exports.render = function (src) {
	let options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
	const locals = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};

  // Bring the locals into the compile options.
	options = _extends({}, options, locals);
	return _coffeescript2.default.compile(src, options);
};
